{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "mender.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-20"
    helm.sh/hook-delete-policy: before-hook-creation
  {{- with .Values.serviceAccount.annotations }}
    {{- tpl (toYaml . | nindent 4) $ }}
  {{- end }}
  name: {{ include "mender.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
