apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../../../base/mender-app/
  - mongodb-efs.yaml

generatorOptions:
 disableNameSuffixHash: true

helmGlobals:
  chartHome: ../../../charts

helmCharts:
- name: mongodb
  releaseName: mongodb
  namespace: mender
  valuesFile: ./mongodb.yaml
  includeCRDs: false
  version: v1.18.2

images:
- name: "docker.io/bitnami/mongodb"
  newName: "194722422560.dkr.ecr.us-east-1.amazonaws.com/bitnami/mongodb"
  newTag: "8.0.11-debian-12-r0"

- name: "docker.io/bitnami/nginx"
  newName: "194722422560.dkr.ecr.us-east-1.amazonaws.com/bitnami/mongodb"
  newTag: "1.29.0-debian-12-r2"

- name: "docker.io/bitnami/kubectl"
  newName: "194722422560.dkr.ecr.us-east-1.amazonaws.com/bitnami/mongodb"
  newTag: "1.33.2-debian-12-r3"

- name: "docker.io/bitnami/os-shell"
  newName: "194722422560.dkr.ecr.us-east-1.amazonaws.com/bitnami/mongodb"
  newTag: "12-debian-12-r47"

- name: "docker.io/bitnami/mongodb-exporter"
  newName: "194722422560.dkr.ecr.us-east-1.amazonaws.com/bitnami/mongodb"
  newTag: "0.45.0-debian-12-r4"
