apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../../../base/mender-app/
  - mongodb-efs.yaml
  - nats-efs.yaml
  - redis-efs.yaml
  - mongodb-secret.yaml
  - redis-secret.yaml
  - nats-secret.yaml




generatorOptions:
 disableNameSuffixHash: true

helmGlobals:
  chartHome: ../../../charts

helmCharts:
- name: mongodb
  releaseName: mongodb
  namespace: mender
  valuesFile: ./mongodb.yaml
  includeCRDs: true
  version: ~14.13.0

- name: nats
  releaseName: nats
  namespace: mender
  valuesFile: ./nats.yaml
  includeCRDs: true
  version: ~0.19.17


- name: redis
  releaseName: redis
  namespace: mender
  valuesFile: ./redis.yaml
  includeCRDs: true
  version: ~17.11.2


- name: mender
  releaseName: mender
  namespace: mender
  valuesFile: ./mender.yaml
  includeCRDs: true
  version: v4.0.1