apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
  - ../../../base/mender-app/
  - mongodb-efs.yaml
  - mongodb-secret.yaml
  - nats-efs.yaml

generatorOptions:
 disableNameSuffixHash: true

helmGlobals:
  chartHome: ../../../charts

helmCharts:
- name: mongodb
  releaseName: mongodb
  namespace: mender
  valuesFile: ./mongodb.yaml
  includeCRDs: false
  version: v1.18.2

- name: nats
  releaseName: nats
  namespace: mender
  valuesFile: ./nats.yaml
  includeCRDs: false


