--- ## Mender NATS Data EFS ## ----

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-nats-data-pv 
spec:
  storageClassName: efs-mender-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxx::fsap-xxxx
    volumeAttributes:
      encryptInTransit: "false"


# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: efs-nats-data-pvc
#   namespace: mender
#   annotations: 
#     volume.beta.kubernetes.io/storage-class: "efs-mender-sc"
# spec:
#   accessModes:
#     - ReadWriteMany
#   storageClassName: efs-mender-sc
#   resources:
#     requests:
#       storage: 10Gi
#   volumeName: efs-nats-data-pv
