--- ## Mender REDIS Replica EFS ## ----

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-redis-replica-pv 
spec:
  storageClassName: efs-mender-sc
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0314c6b7168dd797e::fsap-03442cc0a9c633eaf
    volumeAttributes:
      encryptInTransit: "false" 


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-redis-replica-pvc
  namespace: mender
  annotations: 
    volume.beta.kubernetes.io/storage-class: "efs-mender-sc"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-mender-sc
  resources:
    requests:
      storage: 8Gi
  volumeName: efs-redis-replica-pv




--- ## Mender REDIS Master EFS ## ----

apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-redis-master-pv 
spec:
  storageClassName: efs-mender-sc
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0314c6b7168dd797e::fsap-0dccf71ca4f043d05
    volumeAttributes:
      encryptInTransit: "false" 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-redis-master-pvc
  namespace: mender
  annotations: 
    volume.beta.kubernetes.io/storage-class: "efs-mender-sc"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: efs-mender-sc
  resources:
    requests:
      storage: 8Gi
  volumeName: efs-redis-master-pv
