apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---

kind: Namespace
apiVersion: v1
metadata:
  name: aws-observability
  labels:
    aws-observability: enabled


---

kind: Namespace
apiVersion: v1
metadata:
  name: mender
  labels:
    aws-observability: enabled

