apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources: 
  - ../../../base/controllers/
  # Disabling since passwords and critical data got masked. 
  # If you need to update secrets and efs, add the right account ID access_points id's,  domains and emails. 
  # - issuer-letsencrypt.yaml



generatorOptions:
 disableNameSuffixHash: true

helmGlobals:
  chartHome: ../../../charts

helmCharts:
- name: cert-manager
  releaseName: cert-manager
  namespace: cert-manager
  valuesFile: ./cert-manager.yaml
  includeCRDs: false
  version: v1.18.2

- name: aws-load-balancer-controller
  releaseName: aws-load-balancer-controller
  namespace: kube-system
  valuesFile:  ./aws-load-balancer-controller.yaml
  includeCRDs: false
  version: v2.13.3