apiVersion: v2
appVersion: v4.0.1
description: Mender is a robust and secure way to update all your software and
  deploy your IoT devices at scale with support for customization
name: mender
version: 6.7.0
keywords:
  - mender
  - iot
  - ota
home: https://mender.io
icon: https://github.com/mendersoftware/mender/raw/master/mender_logo.png
sources:
  - https://github.com/mendersoftware/mender-helm
maintainers:
  - name: Northern.tech AS
    email: contact@northern.tech
    url: https://northern.tech
dependencies:
  - name: redis
    repository: "file://../redis"
    tags:
    - redis
    condition: redis.enabled
    version: 21.2.10
  - name: nats
    repository: "file://../nats"
    tags:
    - nats
    condition: nats.enabled
    version: 1.3.9
  - name: mongodb
    repository: "file://../mongodb"
    tags:
    - mongodb
    condition: mongodb.enabled
    version: 16.5.29