name: Scale Up Mender Namespace and Node Group

on:
  workflow_dispatch:

jobs:
  scale-up:
    name: Scale Up Deployments, StatefulSets & Node Group
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --region ${{ secrets.AWS_REGION }} \
            --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Scale Node Group back to 8
        run: |
          aws eks update-nodegroup-config \
            --cluster-name ${{ secrets.EKS_CLUSTER_NAME }} \
            --nodegroup-name ${{ secrets.EKS_NODEGROUP_NAME }
